apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pupweb
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: pupweb
    spec:
      containers:
      - name: pupweb
        image: fluxtestregistry.azurecr.io/pupweb/pubweb:latest
        ports:
        - containerPort: 5000
---

# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pupweb
  labels:
    app: pupweb
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: pupweb