apiVersion : apps/v1
kind: Deployment
metadata:
  name: "pythonbootcamp-9a14"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "pythonbootcamp-9a14"
  template:
    metadata:
      labels:
        app: "pythonbootcamp-9a14"
    spec:
      containers:
        - name: "pythonbootcamp-9a14"
          image: "python9292.azurecr.io/pythonbootcamp"
          ports:
          - containerPort: 80