apiVersion: v1
kind: Service
metadata:
    name: "cicdnginx-deb5"
    labels:
        app: "cicdnginx-deb5"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "cicdnginx-deb5"