---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pupweb
spec:
  selector:
    matchLabels:
      app: pupweb
  replicas: 4
  template:
    metadata:
      labels:
        app: pupweb
    spec:
      containers:
      - name: pupweb
        image: fluxtestregistry.azurecr.io/pupweb/pubweb
        ports:
        - containerPort: 5000